upstream mis_servidores_web {
    server 10.0.20.21:80;
    server 10.0.20.22:80;
}

server {
    listen 80 default_server;

    location / {
        proxy_pass http://mis_servidores_web;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
