name: Pipeline CD - Despliegue Automatizado Remoto

on:
  push:
    branches:
      - master  # <-- Asegúrate de que coincida con tu rama (master o main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Transferir index.php al Balanceador local vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22  # <-- Forzamos el puerto SSH nativo de localhost.run directamente
          source: "./index.php"
          target: "/root/"

      - name: Ejecutar comandos de ordenamiento dentro de tu WSL
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Moviendo el código desde el Balanceador hacia los Nodos Web..."
            
            # Ahora que el archivo llegó a srv-lb-tf, lo repartimos internamente en tu red virtual
            lxc file push /root/index.php srv-web-tf-1/root/index.php
            lxc file push /root/index.php srv-web-tf-2/root/index.php
            
            # Ajustar permisos y reiniciar microservicios en caliente
            lxc exec srv-web-tf-1 -- chmod 644 /root/index.php
            lxc exec srv-web-tf-2 -- chmod 644 /root/index.php
            lxc exec srv-web-tf-1 -- docker restart mi-servidor-web-1
            lxc exec srv-web-tf-2 -- docker restart mi-servidor-web-2
            
            echo "✨ ¡Despliegue global completado con éxito!"
